# Generated by Django 4.1.7 on 2023-02-17 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id_product",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_product", models.CharField(max_length=255)),
                ("describe_product", models.CharField(max_length=255)),
                ("image_product", models.ImageField(upload_to="")),
                ("creat_at", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
