# Generated by Django 4.1.7 on 2023-02-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_product',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
