# Generated by Django 4.1.7 on 2023-02-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_product_price_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_user", models.CharField(max_length=255)),
                ("price_historic", models.FloatField()),
                ("date_historic", models.DateField(auto_now_add=True)),
                ("products_historic", models.JSONField()),
            ],
        ),
    ]
