# Generated by Django 4.1.7 on 2023-02-20 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_historic_id_alter_historic_id_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="historic",
            name="quantity",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
